import uuid from 'uuid/v4';

export default [
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false},
    {id:uuid(), task:'Fazer XYZ', done:false},
    {id:uuid(), task:'Fazer ABC', done:true},
    {id:uuid(), task:'Fazer YUI', done:false}
];